### ISSUE TITLE
Ajout de l'option delete sur le tag @develop 

### ISSUE THREAD

**Issue by FlorianMichonneau** [kestra-io/deploy-action#5]
Hello la team Kestra,

Je n'arrive plus à delete les fichiers non présents sur mon repos mais présents sur kestra en utilisant le tag @develop de la github action pour deploy.

Actuellement il y a : 

_#Check if we delete or not resources
delete=""
if [[ $7 == false ]]; then
  delete="--no-delete"
fi_

dans le fichier entrypoint.sh du tag @develop

Est-ce possible d'intégrer les dernières modifications du repos dans le tag @develop ?

Merci d'avance :)
Bien à vous,
Florian

**Comment by Skraye** [comment]
Hello, 
On a désormais un tag par version (donc v0.0.1 et v0.0.2 pour l'instant) et une develop qui sera mis à jour à chaque changements :
https://github.com/kestra-io/deploy-action/releases

N'hésites pas s'il manque quoi que ce soit.
